name: subman
description: "SubMan - Subscription Manager App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  http: ^1.2.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  table_calendar: ^3.1.1
  fl_chart: ^0.66.2
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.5.4
  image_picker: ^1.2.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
